table DetailedProjects
	lineageTag: d68df17a-b4f0-4db5-a6ff-2e79beca0835

	column Category
		dataType: string
		lineageTag: c42710e2-be26-462d-b6ed-0a74e3fbf59c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column 'Site '
		dataType: string
		lineageTag: ed6a2476-e4ba-4848-9977-0fbc9d4f1b1e
		summarizeBy: none
		sourceColumn: "Site "

		annotation SummarizationSetBy = Automatic

	column #
		dataType: string
		lineageTag: 78980f58-27fd-4574-ae4c-c04cb80bbe4f
		summarizeBy: none
		sourceColumn: #

		annotation SummarizationSetBy = Automatic

	column 'ID Tracker'
		dataType: string
		lineageTag: 0b883308-a4cd-4cce-81d5-32c890c87988
		summarizeBy: none
		sourceColumn: ID Tracker

		annotation SummarizationSetBy = Automatic

	column Initiatives
		dataType: string
		lineageTag: d0ed7058-aa23-4735-98f0-5d54643c967b
		summarizeBy: none
		sourceColumn: Initiatives

		annotation SummarizationSetBy = Automatic

	column Lead
		dataType: string
		lineageTag: 44e08e87-b1d6-4349-9e21-8ca858a6a547
		summarizeBy: none
		sourceColumn: Lead

		annotation SummarizationSetBy = Automatic

	column Plan
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: b515f8ee-7537-48b2-8781-d339f2b6a9ca
		summarizeBy: none
		sourceColumn: Plan

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Actual
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: df952569-7d06-483c-a7ff-282e41e781b2
		summarizeBy: none
		sourceColumn: Actual

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Comments
		dataType: string
		lineageTag: 21cfb8f6-6681-4a8c-9543-fda372da0879
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column Status = ```
			
			var ActualMonth = MONTH([Actual])
			var PlanMonth = MONTH([Plan])
			var CurrentMonth = MONTH(TODAY())
			var fx = 
			    IF(
			        ISBLANK('DetailedProjects'[Plan]), "No SAT Plan", 
			        IF(
			            NOT ISBLANK(ActualMonth),              
			                IF(ActualMonth <= PlanMonth, "On Track","Delay" ) ,
			                IF(CurrentMonth <= PlanMonth,"On Track","Delay")
			        )
			    )
			RETURN
			    fx
			
			```
		lineageTag: cc73df64-a2b9-4d1f-9433-7e379096b463
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DetailedProjects = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://legogroup.sharepoint.com/sites/globalprocessingwheel/Projects/Productivity%202024/All%20identified%20activities%20Global%20PW%202025/All%20identified%20activities%20Global%20PW%202025%20Rev3.xlsx"), null, true),
				    #"Initiatives tracking '25_Sheet" = Source{[Item="Initiatives tracking '25",Kind="Sheet"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(#"Initiatives tracking '25_Sheet", each ([Column2] <> null)),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Filtered Rows", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers",{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "Column11", "Lead_1", "Plan_2", "Projected", "Column15", "Column17", "Column16", "Network's support", "Column73", "Quality", "2025 Saving", "Column7", "Column71"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"Plan", type date}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each ([Initiatives] <> null)),
				    #"Sorted Rows" = Table.Sort(#"Filtered Rows1",{{"Site ", Order.Ascending}, {"Lead", Order.Ascending}, {"Category", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

